kind: pipeline
type: docker
name: deploy-Maakplaats

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 100.87.222.51
      username: deploy
      key:
        from_secret: ssh_private_key
      script:
        - cd /opt/apps || mkdir -p /opt/apps
        - rm -rf /opt/apps/Maakplaats
        - git clone http://100.73.19.6:3000/devdesli/Maakplaats.git /opt/apps/Maakplaats
        - cd /opt/apps/Maakplaats
        - docker build -t maakplaats:latest .
        - docker stop maakplaats || true
        - docker rm maakplaats || true
        - docker run -d --name maakplaats -p 5000:5000 maakplaats:latest
